/* ── BUILD THE ROOMS' EDITS (6 Oct 2026) ─────────────────────────────────
   node scripts/edits/build.mjs   (npm run edits:build)
   Assembles public/lab/density/edits.js from every scripts/edits/<k>.json,
   one study per file, each file { k, variants: { index, trim?, fold? } }.
   study-panel.js reads it under ?edit=index (and trim, fold, today). */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(HERE, "../../public/lab/density/edits.js");
/* with study keys (node build.mjs sally-os ...), only those are rebuilt and
   every other study keeps what edits.js already holds, so a study someone
   is still writing never ships half done */
const only = process.argv.slice(2);
const files = fs.readdirSync(HERE).filter((f) => f.endsWith(".json") && !f.startsWith(".") && (!only.length || only.includes(f.replace(/\.json$/, "")))).sort();
const out = {};
if (only.length && fs.existsSync(OUT)) {
  const ctx = { window: {} };
  new Function("window", fs.readFileSync(OUT, "utf8"))(ctx.window);
  Object.assign(out, ctx.window.DENSITY_EDITS || {});
}
for (const f of files) {
  const E = JSON.parse(fs.readFileSync(path.join(HERE, f), "utf8"));
  const k = E.k || f.replace(/\.json$/, "");
  if (!E.variants || !E.variants.index) { console.error("skip " + f + ": no index variant"); continue; }
  out[k] = E.variants;
}
const head = `/* ── A STUDY'S EDITS ───────────────────────────────────────────────────────
   GENERATED by scripts/edits/build.mjs from scripts/edits/<study>.json; do
   not edit by hand. The standard is scripts/edits/BRIEF.md (his "this copy
   direction is SO much more straightforward, can we make this our standard
   going forward?", 6 Oct 2026). study-panel.js sets a study's words from
   here under ?edit=index (and ?edit=trim, ?edit=fold where a study has
   them; ?edit=today is the room as it was, with the switch). Every string
   is the study's own: a line of it, a trim of one, or two joined. */
window.DENSITY_EDITS = `;
fs.writeFileSync(OUT, head + JSON.stringify(out, null, 1) + ";\n");
console.log("wrote edits.js: " + Object.keys(out).length + " studies (" + Object.keys(out).join(", ") + ")");
