/* ── SIGNAL, AS A ROOM OF THE SITE (6 Oct 2026) ──────────────────────────
   node scripts/build-signal.mjs   (npm run signal)
   His "i want it worked into this version of the site", then "doesnt have
   to be styled like the daybook". Reads src/data/signal.ts (the entries,
   his takes, the page's own sentence) and writes public/lab/density/
   signal.js: window.DENSITY_ROOMS.signal, a room the index opens the way
   it opens a study, kept out of the studies' data so it never counts as
   work, a year or a figure. Its words are fragments in the studies'
   shape: the sentence as the subtitle, each entry a section (its day and
   source the label, the headline the title, his take the text, a link to
   the source). Run it after editing src/data/signal.ts. */
import fs from "node:fs";
import path from "node:path";
import ts from "typescript";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const load = (rel) => {
  const src = fs.readFileSync(path.join(ROOT, rel), "utf8");
  const js = ts.transpileModule(src, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 } }).outputText;
  const module = { exports: {} };
  new Function("module", "exports", "require", js)(module, module.exports, () => ({}));
  return module.exports;
};
const S = load("src/data/signal.ts");
const NEWEST = S.NEWEST || S.SIGNAL;
const clean = (s) => String(s == null ? "" : s).replace(/\s+/g, " ").trim();

const frags = [];
let pi = 1, n = 0;
const nid = () => "sg" + (n++).toString(36);
frags.push({ id: nid(), k: "signal", kind: "line", si: 1, pi: pi++, text: clean(S.SIGNAL_LEDE) + " | " + clean(S.SIGNAL_DIM), weight: "sub", where: "meta" });
/* the page's tail and its rule for the notes, in the page's own words */
const a = pi++;
frags.push({ id: nid(), k: "signal", kind: "line", si: 1, pi: a, text: clean(S.SIGNAL_TAIL), weight: "body", where: "abstract" });
frags.push({ id: nid(), k: "signal", kind: "line", si: 1, pi: a, text: "The headline is the source’s. The note under it is mine, from building with these tools.", weight: "body", where: "abstract" });
NEWEST.forEach((e, i) => {
  const si = 2 + i;
  frags.push({ id: "sg-" + e.id, k: "signal", kind: "line", si, pi: pi++, text: clean(e.headline), label: S.dayHead(e.date) + " · " + clean(e.source), weight: "head", where: "section-header" });
  (Array.isArray(e.take) ? e.take : [e.take]).forEach((t) => frags.push({ id: nid(), k: "signal", kind: "line", si, pi: pi++, text: clean(t), weight: "body", where: "text" }));
  frags.push({ id: nid(), k: "signal", kind: "src", si, pi: pi++, url: e.sourceUrl, text: "Read it at " + clean(e.source) });
});
const study = { k: "signal", h: "signal", t: "Signal", s: "AI news, with my notes", y: +String(NEWEST[0].date).slice(0, 4), tags: [],
  fact: clean(S.SIGNAL_LEDE), rest: clean(S.SIGNAL_DIM), palette: null, fill: "#ECECEC", ink: "#000000", lead: null, top: null };
const entries = NEWEST.map((e) => ({ id: e.id, at: "sg-" + e.id, date: e.date, day: S.dayHead(e.date), headline: clean(e.headline), source: clean(e.source),
  url: e.sourceUrl, take: (Array.isArray(e.take) ? e.take : [e.take]).map(clean).join(" "), tags: e.tags }));
const out = `/* GENERATED by scripts/build-signal.mjs from src/data/signal.ts; do not edit by hand */
window.DENSITY_ROOMS = window.DENSITY_ROOMS || {};
window.DENSITY_ROOMS.signal = ${JSON.stringify({ study, frags, entries }, null, 1)};
`;
fs.writeFileSync(path.join(ROOT, "public/lab/density/signal.js"), out);
console.log("wrote signal.js: " + entries.length + " entries, " + frags.length + " fragments");
