/* ── SIGNAL, AS A ROOM OF THE SITE (6 Oct 2026) ──────────────────────────
   node scripts/build-signal.mjs   (npm run signal)
   His "i want it worked into this version of the site", then "doesnt have
   to be styled like the daybook". Reads src/data/signal.ts (the entries,
   his takes, the page's own sentence) and writes public/lab/density/
   signal.js: window.DENSITY_ROOMS.signal, a room the index opens the way
   it opens a study, kept out of the studies' data so it never counts as
   work, a year or a figure. Its words are fragments in the studies'
   shape: the sentence as the subtitle, each entry a section (its day and
   source the label, the headline the title, his take the text, a link to
   the source, and a link to the study it touches when it names one). Run
   it after editing src/data/signal.ts.

   DRAFTS (6 Oct 2026, his "can you do some posts on the signals page
   while i'm gone? ... think of a structure per post? almost a content
   strategy maybe?"): src/data/signal-drafts.ts holds posts waiting for
   his read, each with the facts it stands on and what to ask him. They
   build into public/lab/density/signal-drafts.js, a second room read at
   /?drafts#study/signal-drafts; that file is ignored by git, so drafts
   never ship. SIGNAL.md is the strategy. */
import fs from "node:fs";
import path from "node:path";
import ts from "typescript";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const load = (rel) => {
  const src = fs.readFileSync(path.join(ROOT, rel), "utf8");
  const js = ts.transpileModule(src, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 } }).outputText;
  const module = { exports: {} };
  const req = (p) => (/\/signal$/.test(p) ? load("src/data/signal.ts") : {});
  new Function("module", "exports", "require", js)(module, module.exports, req);
  return module.exports;
};
const S = load("src/data/signal.ts");
const clean = (s) => String(s == null ? "" : s).replace(/\s+/g, " ").trim();
const lines = (t) => (Array.isArray(t) ? t : [t]).map(clean).filter(Boolean);

/* the studies a post can point at, by key, with the names the rooms use */
const STUDY_NAME = { arc: "A.R.C.", "sally-os": "Sally Marketing OS", dsc: "Dallas Sport Collective", sizzle: "Faux Reel", "sally-design-system": "the Sally design system" };

const room = (key, { title, sub, lede, dim, tail, rule, entries, label, extra }) => {
  const frags = [];
  let pi = 1, n = 0;
  const nid = () => (key === "signal" ? "sg" : "sd") + (n++).toString(36);
  frags.push({ id: nid(), k: key, kind: "line", si: 1, pi: pi++, text: clean(lede) + " | " + clean(dim), weight: "sub", where: "meta" });
  const a = pi++;
  frags.push({ id: nid(), k: key, kind: "line", si: 1, pi: a, text: clean(tail), weight: "body", where: "abstract" });
  if (rule) frags.push({ id: nid(), k: key, kind: "line", si: 1, pi: a, text: clean(rule), weight: "body", where: "abstract" });
  entries.forEach((e, i) => {
    const si = 2 + i;
    frags.push({ id: "sg-" + e.id, k: key, kind: "line", si, pi: pi++, text: clean(e.headline), label: label(e), weight: "head", where: "section-header" });
    lines(e.take).forEach((t) => frags.push({ id: nid(), k: key, kind: "line", si, pi: pi++, text: t, weight: "body", where: "text" }));
    const note = extra ? extra(e) : [];
    if (note.length) frags.push({ id: nid(), k: key, kind: "note", si, pi: pi++, title: "To check", items: note });
    const links = [{ url: e.sourceUrl, text: "Read it at " + clean(e.source) }];
    if (e.study && STUDY_NAME[e.study]) links.push({ url: "#study/" + e.study, text: "See it in " + STUDY_NAME[e.study] });
    frags.push({ id: nid(), k: key, kind: "src", si, pi: pi++, url: links[0].url, text: links[0].text, links });
  });
  const y = entries.length && entries[0].date ? +String(entries[0].date).slice(0, 4) : 2026;
  const study = { k: key, h: key, t: title, s: sub, y, tags: [], fact: clean(lede), rest: clean(dim), palette: null, fill: "#ECECEC", ink: "#000000", lead: null, top: null };
  const list = entries.map((e) => ({ id: e.id, at: "sg-" + e.id, date: e.date || null, day: e.date ? S.dayHead(e.date) : null, headline: clean(e.headline), source: clean(e.source),
    url: e.sourceUrl, take: lines(e.take).join(" "), tags: e.tags || [], study: e.study || null }));
  return { study, frags, entries: list };
};
const write = (file, key, data, from) => {
  const out = `/* GENERATED by scripts/build-signal.mjs from ${from}; do not edit by hand */
window.DENSITY_ROOMS = window.DENSITY_ROOMS || {};
window.DENSITY_ROOMS[${JSON.stringify(key)}] = ${JSON.stringify(data, null, 1)};
`;
  fs.writeFileSync(path.join(ROOT, file), out);
  console.log("wrote " + path.basename(file) + ": " + data.entries.length + " entries, " + data.frags.length + " fragments");
};

/* the room on the site */
const NEWEST = S.NEWEST || S.SIGNAL;
write("public/lab/density/signal.js", "signal", room("signal", {
  title: "Signal", sub: "AI news, with my notes", lede: S.SIGNAL_LEDE, dim: S.SIGNAL_DIM, tail: S.SIGNAL_TAIL,
  rule: "The headline is the source’s. The note under it is mine, from building with these tools.",
  entries: NEWEST, label: (e) => S.dayHead(e.date) + " · " + clean(e.source),
}), "src/data/signal.ts");

/* the drafts, for his read only (ignored by git) */
if (fs.existsSync(path.join(ROOT, "src/data/signal-drafts.ts"))) {
  const DR = load("src/data/signal-drafts.ts");
  const drafts = DR.SIGNAL_DRAFTS || [];
  const KIND = DR.KIND_NAME || {};
  write("public/lab/density/signal-drafts.js", "signal-drafts", room("signal-drafts", {
    title: "Signal drafts", sub: "For Jeremy to read aloud",
    lede: "Drafts for Signal, written from your projects while you were away.",
    dim: "Each stands on facts from the studies, the daybook and the apps' own notes; what's under a note is what only you can confirm.",
    tail: "The order is the order I would post them in. SIGNAL.md has the strategy behind them.",
    entries: drafts,
    label: (e) => (KIND[e.kind] || "Draft") + " · " + clean(e.source),
    extra: (e) => (e.ask || []).map(clean),
  }), "src/data/signal-drafts.ts");
}
