/**
 * Inspiration board quotes — text-only tiles woven into the image masonry.
 *
 * These are intentionally curated rather than scripted. The image list at
 * src/data/inspiration.ts is auto-regenerated by scripts/build-inspiration.py
 * from folder contents — keeping quotes in a separate file means the script
 * doesn't clobber them on each run.
 *
 * Positions are the indices in the merged item array where each quote
 * lands. They're treated as anchors — early / quarter / middle / three-
 * quarters / late — so the spacing stays sensible as the image count grows.
 *
 * Voice direction: short and earned, not aphorism-stacking. Lean on the
 * voice-references library for tone (Pentagram, Simmons, Chimero, Rams,
 * Anthropic research register). Stay confident in attribution — only ship
 * a quote whose source is verifiable.
 */

export interface InspirationQuote {
  type: "quote";
  text: string;
  attribution: string;
}

export const inspirationQuotes: InspirationQuote[] = [
  {
    type: "quote",
    // Multi-line preserved via \n — tile renders with whitespace-pre-line.
    text: "Came up on a tornado, sunlight in the sky\nI went around all day with the moon sticking in my eye",
    attribution: "Don Van Vliet, Captain Beefheart",
  },
  {
    type: "quote",
    // Single \n between lines — return per line, not a blank stanza gap.
    text: "And this old man in front of me wearing canes and ruby rings\nIt's like containing an explosion when he sings\nWith every chance to set himself on fire\nHe just ends up doing the same thing",
    attribution: "Jack White",
  },
  {
    type: "quote",
    text: "What you got ain't nothin' new. This country is hard on people. You can't stop what's coming. It ain't all waiting on you. That's vanity.",
    attribution: "Cormac McCarthy",
  },
];

/**
 * Insertion points in the merged item list (image index BEFORE which each
 * quote should appear). Adjust to taste — these are early/middle/late
 * anchors with the current ~100-image board. If the list grows past 200
 * consider switching to fraction-based math instead of fixed indexes.
 */
export const quoteInsertionPoints = [5, 38, 90];
